[package]
name = "univis_editor_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
serde.workspace = true
univis_ui.workspace = true
univis_graph_core = { path = "../univis_graph_core" }
univis_node_graph = { path = "../univis_node_graph" }
univis_editor_commands = { path = "../univis_editor_commands" }
univis_editor_runtime = { path = "../univis_editor_runtime" }
