[package]
name = "univis_editor_app"
version = "0.1.0"
edition = "2024"

[features]
default = ["craft", "legacy"]
craft = []
legacy = []

[dependencies]
bevy.workspace = true
serde.workspace = true
serde_json.workspace = true
univis_ui.workspace = true
univis_node_graph = { path = "../univis_node_graph" }
univis_scene = { path = "../univis_scene" }
univis_editor_runtime = { path = "../univis_editor_runtime" }
univis_editor_ui = { path = "../univis_editor_ui" }
univis_editor_persistence = { path = "../univis_editor_persistence" }
univis_editor_nodes_builtin = { path = "../univis_editor_nodes_builtin" }

[[example]]
name = "simple_editor"
path = "../../examples/simple_editor.rs"

[[example]]
name = "custom_nodes"
path = "../../examples/custom_nodes.rs"

[[example]]
name = "custom_visual_node"
path = "../../examples/custom_visual_node.rs"

[[example]]
name = "custom_scene_node"
path = "../../examples/custom_scene_node.rs"
