[package]
name = "univis_node_graph"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
serde.workspace = true
serde_json.workspace = true
typetag.workspace = true
inventory.workspace = true
univis_graph_core = { path = "../univis_graph_core" }
univis_scene = { path = "../univis_scene" }
